language: node_js

os: linux

node_js:
  - 8

notifications:
  email:
    on_failure: change

install:
  - yarn

cache:
  yarn: true
  directories:
    - node_modules

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    local_dir: dpl_cd_upload
    skip_cleanup: true
    on: &2
      repo: rafalsep/blog
    bucket: blog-front
    region: eu-central-1
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: blog-front
    key: latest.zip
    bundle_type: zip
    application: blogFrontEnd
    deployment_group: blog
    region: eu-central-1
    on: *2

script:
  - yarn run lint
  - yarn run test
  - yarn run build
  - zip -r latest build/* appspec.yml server/* package.json
  - mkdir -p dpl_cd_upload
  - mv latest.zip dpl_cd_upload/latest.zip
