export const FETCH_ARTICLE_RESPONDED = 'FETCH_ARTICLE_RESPONDED';
export const FETCH_ARTICLES_RESPONDED = 'FETCH_ARTICLES_RESPONDED';
export const FETCH_TRENDING_ARTICLES_RESPONDED = 'FETCH_TRENDING_ARTICLES_RESPONDED';
